DEFRA/ivory

docker-compose.yml
This is needed so localhost can see the port.
=> Add ports to docker compose

server/views/layout.html
Some users might not have JavaScript enabled, hence for these users the back link must be hidden.
=> Hide back link for non-JS users

.env.example, README.md, package-lock.json, package.json, server/index.js, server/plugins/logging.plugin.js, server/routes/check-your-answers.route.js, server/routes/home.route.js, server/routes/ivory-added.route.js, server/routes/ivory-integral.route.js, server/routes/taken-from-elephant.route.js, server/services/redis.service.js, server/utils/config.js, server/utils/constants.js, server/utils/cookieConfig.js, server/views/check-your-answers.html, server/views/ivory-integral.html, server/views/yes-no-idk.html
IVORY-306: Make data stored in Redis session-specific
Added creation of a session cookie to the home page.
Generated a unique session ID and added to the session cookie.
Appended session ID to Redis keys using the following format:
sessionId.redisKey
e.g. 91bde99f-c98e-4ff7-8d87-b786b8fb6eb4.ivory-added
Created a RedisService responsible for getting and setting Redis valus and setting expiry (Time To Live / TTL) on values stored Redis. Currently hard-coded to 86400 (i.e. one day in seconds). This could be made a configurable parameter if required.
Also, added novalidate to forms to turn off HTML5 validation as per GDS guidelines.
Submitting draft PR for now, unit tests to follow if the implementation method in this PR is accepted.
=> Session-specific Redis storage

.env.example, server/plugins/logging.plugin.js, server/utils/config.js, server/views/user-details/contact-details.html, test/routes/owner/contact-details.route.test.js, test/services/redis.service.test.js, test/utils/test-helper.js
Fixed bug IVORY-314 (hint text not appearing on 'Your contact details' page).
Added unit tests for the Redis service and contact-details route. 
Also, made the log level a separate config item (defaults to 'warn') because with debug mode turned on in development, like it was by default, the amount of debug info being produced was a bit overwhelming during normal development. If needed a Developer can turn the debug mode back on by setting the log level to 'debug' in their local .env file.
=> IVORY-314 bug fix plus added unit tests for Redis service and contact-details route, log level change

.gitignore, server/routes/ivory-added.route.js, test/routes/ivory-added.route.test.js
Amended page title and error message. Removed the hint text.
Updated unit tests accordingly
=> Ivory 320 make 'ivory has been repaired' question easier

.env.example, README.md, bin/scripts/convertCert.js, server/services/address.service.js
Given that our environments cannot easily use a certificate file to authenticate the address lookup I have created this workaround.
=> Allow address lookup cert to be a Base64 string

server/services/payment.service.js
IVORY 336 and 337 - return URL not working
Removed separate PORT from return URL, now provided as part of the SERVICE_HOST environment variable if needed
e.g.SERVICE_HOST=http://localhost:3000
=> GOV Pay return URL fix

server/routes/common/address-choose.route.js, server/routes/common/address-confirm.route.js, server/routes/common/address-enter.route.js, server/routes/common/address-find.route.js, server/utils/constants.js, server/views/user-details/address-choose.html, test/routes/applicant/address-choose.route.test.js, test/routes/applicant/address-find.route.test.js, test/routes/owner/address-choose.route.test.js, test/routes/owner/address-find.route.test.js
IVORY-327
Added help text to choose-address screen, only visible when a building name / number value and postcode has been entered in the find-address screen but there are no matching addresses.
To facilitate this the nameOrNumber and postcode fields are stored in Redis in the find-address screen and then accessed in the choose-address screen.
=> IVORY-327: Added help text to choose-address screen.

server/routes/common/address-international.route.js, server/views/user-details/address-choose.html, server/views/user-details/address-international.html, test/routes/applicant/address-international.route.test.js, test/routes/owner/address-international.route.test.js, test/utils/test-helper.js
Reworked address-international so that the help text is rendered as a separate P tag in black text rather than grey hint text.
=> International Address screen help text

server/routes/common/address-enter.route.js, server/views/user-details/address-choose.html
IVORY-339
Addresses coming back from the address API can have a combination of one or more different values that make up the first line of the address:
BuildingName, SubBuildingName, BuildingNumber, Street
Any of these may be missing.
This change parses the above fields and builds up a comma-separated addressLine1 according to which one of these are present in the address.
=> Improvements to address parsing

server/routes/common/address-find.route.js
Fixed a bug I noticed during prep for the last demo.
In the Find Address screen, whatever postcode the user has input needs to be saved in Redis in upper case, as it gets played back to them in the Choose Address screen if they have entered a building name or house number that isn't matched.
=> Convert input postcode to uppercase

server/views/user-details/address-find.html
IVORY-354
Made the form field labels bold for property name or number and postcode on the /find-address screen.
=> Address pattern - make form fields more prominent

server/routes/check-your-answers.route.js, server/routes/describe-the-item.route.js, server/routes/upload-photos.route.js, server/routes/what-type-of-item-is-it.route.js, server/routes/who-owns-the-item.route.js, server/utils/constants.js, server/views/check-your-answers.html, server/views/describe-the-item.html, server/views/upload-photos.html, server/views/who-owns-the-item.html, test/routes/describe-the-item.route.test.js
IVORY-352: Describe the item page
This change adds the content for the /describe-the-item page.
Included is a function called _addRedisDataToContext. This is responsible for populating the page on GET if we are returning there later, e.g. from Check Your Answers.
A similar fix has been carried out on the following pages:
- what-type-of-item-is-it
- who-owns-the-item
Also included is an increase to the request timeout on the Upload page to 2 minutes to fix a problem that occurred when uploading large files.
=> Describe the item page (S10 and S2 descriptions)

.env.example, README.md, server/plugins/redis.plugin.js, server/utils/config.js
Added Redis password environment variable for use when deploying to Azure environments.
N.B. - Now gives the following warning locally but still seems to work OK:
[WARN] This Redis server's `default` user does not require a password, but a password was supplied
=> Add Redis password environment variable

package.json, server/plugins/error-pages.plugin.js, server/routes/errors/page-not-found.route.js
When basic authentication is turned on, the server writes information to the console whenever the user is prompted for their username and password. These error logs are unnecessary and misleading, as the authentication server error was handled normally, therefore it makes sense to suppress this error logging.
Another thing that was added was a "catch all" for 404 errors (page not found), because otherwise if basic authentication is turned on, the login prompt appears and the user presses 'cancel' then a 404 error occurs. Adding this catch-all prevents that from happening.
=> Suppress logging of 401 errors

server/routes/can-continue.route.js, server/routes/eligibility-checker/how-certain.route.js, server/utils/constants.js, server/views/can-continue.html, test/routes/can-continue.route.test.js, test/routes/eligibility-checker/how-certain.route.test.js
IVORY-368
The can-continue route has been updated. There is now new copy that is dynamic based on two conditions:
1. Whether or not it is a Section 2 item
2. Whether or not the user has used the eligibility checker
=> Update can-continue route to match new dynamic copy

package.json, server/views/upload-photos.html, test/routes/upload-photos.route.test.js, test/services/active-directory-auth.service.test.TODO.js, test/utils/test-helper.js
Fixed bug in /upload-photos screen, some helptext should always be displayed regardless of how many images have been uploaded. This is now fixed.
=> Fixed missing copy on image upload screen

server/utils/cookie-config.js
IVORY-410
User session cookies should expire after 24 hours.
The cookie timeout specified in the config was not being applied, therefore the cookies would not time out in any browser. This is now fixed.
=> Fixed cookie timeout problem - config not being applied.

.env.example, server/plugins/views.plugin.js
IVORY-426: Service name not matching Prototype
Service name has been updated to "Declare elephant ivory you intend to sell or hire out"
=> Updated service name

package.json, server/routes/intention-for-item.route.js, server/routes/ivory-integral.route.js, server/routes/ivory-volume.route.js, server/views/intention-for-item.html, server/views/ivory-volume.html, test/routes/intention-for-item.route.test.js, test/routes/ivory-integral.route.test.js, test/routes/ivory-volume.route.test.js
IVORY-441: Populate /intention-for-item screen
IVORY-442: Bug in page flow
IVORY-443: Missing help text on /ivory-volume screen
This fixes an issue when returning to the intention-for-item screen from Check Your Answers - the previously selected value was not being selected when returning to the page.
Also fixes a bug in the page flow for <10% items.
Also adds missing help text on /ivory-volume screen
=> Bug fixes - 441 and 443

package.json, server/routes/legal-responsibility.route.js, test/routes/legal-responsibility.route.test.js
IVORY-444: Modify page flow after visiting Check Your Answers
When at the /legal-responsibility page, if there are already some uploaded photos, the next page is now /your-photos, otherwise the next page is /upload-photo.
=> Modify page flow in /legal-responsibility after visiting Check Your Answers page

server/views/ivory-volume.html, test/routes/ivory-volume.route.test.js
IVORY-443: Remove help text
Revert change that added help text to the /ivory-volume page
=> Revert change that added help text to the /ivory-volume page

package.json, server/routes/save-record.route.js
IVORY-446: Error when saving Museum item type records
When the Item Type is Museam, there was an error saving the record in PowerApps, because empty values were being passed in as empty strings rather than null, which are not valid values.
=> Fixed error when saving Museum item type records

.env.example, server/routes/service-complete.route.js, server/services/notification.service.js, test/routes/service-complete.route.test.js, test/services/notification.service.test.js
IVORY-447: Add S2 confirmation emails
This change adds the sending of confirmation emails for Section 2 applicaitons.
=> Add S2 confirmation emails

package.json, server/utils/config.js, server/utils/upload.js, server/views/upload-document.html, server/views/upload-photo.html, test/routes/upload-document.route.test.js, test/routes/upload-photo.route.test.js
IVORY-419: Error when uploading large documents and images
Initially, documents and images of up to 30MB were allowed. However, this caused a problem when the application was deployed into the Azure infrastructure, due to timeout issues. In order to solve this issue, it has been agreed that the file size limit can be reduced to 10MB.
=> Fixes for error when uploading large documents and images

package-lock.json, package.json
Upgraded dependences. 
Non-breaking changes only - 2 packages remaining for further investigation:
hapi-pino - prettyPrint is deprecated, use the pino-pretty transport instead
node-fetch - node-fetch v3 is ESM-only
=> Upgraded non-breaking dependencies

package.json, server/routes/service-complete.route.js
IVORY-507: Delete session cookie upon journey completion
The user session cookie is now deleted on the Submission Received page once they have successfully submitted their S2 or S10 application, in order to prevent the user from jumping back to a previous page in the flow and altering/resubmitting their application.
=> Deleted session cooke on journey completion

package.json, server/views/layout.html
IVORY-543: Update page title to meet accessibility review requirement from latest review
The page title (i.e. the text that appears when you hover over the browser tab) should include the service name is now in the following format:
page heading - service name - GOV.UK
=> Updated page title to meet new accessiblity requirement

package.json, server/utils/upload.js
IVORY-419: Image and file uploads - "file too large" error message not appearing
While investigating IVORY-419 it was noticed that the "file too large" error message was no longer appearing. This was because the way the boolean values in Redis are saved has recently changed. This is now fixed - the "file too large" error does now appear, but it is unlikely that this has fixed the actual problem reported in IVORY-419, but further investigation of that issue will now be possible.
=> Applied fix for file size error messages not appearing

package.json, server/views/why-is-item-rmi.html, test/routes/why-is-item-rmi.route.test.js
IVORY-548: Why RMI help text bug
Removed word 'on' from the copy to match the specification.
=> Fixed copy bug in why-is-item-rmi page

package.json, server/routes/legal-responsibility.route.js, test/routes/legal-responsibility.route.test.js
IVORY-552: S2 and already certified - Legal halt "help text" some content missing on FE
Some legal help text was missing for already certified S2 applications. This has been added.
=> Legal halt page - added missing help text for S2 already certified applications

package.json, server/views/check-your-answers.html, test/routes/check-your-answers.route.test.js
IVORY-558: Check your answers page - regression issue
Fixed a bug relating to the text displayed for one of the Check your answers page section headings.
=> CYA page - page section copy regression issue

package.json, server/views/eligibility-checker/do-not-need-service.html, test/routes/do-not-need-service.route.test.js
IVORY-596: Remove CITES text
Removed some copy and corresponding unit tests from the /do-not-need-service page.
=> Removed text from do-not-need-service page

package.json, server/views/ivory-volume.html, server/views/share-details-of-item.html, test/routes/share-details-of-item.test.js
IVORY-603: Share details of your item - Missing Content
IVORY-605: Ivory volume - Other reason - Text field NOT displaying 
Fixed a pair of issues where some HTML content wasn't appearing when it should have been.
=> Fix bugs relating to missing HTML content

package.json, server/routes/eligibility-checker/how-certain.route.js, server/routes/home.route.js, test/routes/eligibility-checker/how-certain.route.test.js, test/routes/home.route.test.js
IVORY-604:  Error after share details of item page
The generation of the submission reference has been moved to the beginning of the flow. But it can't be generated on the same page as when the session cookie is created, therefore it has been moved to the next page (/how-certain).
=> Fixed problem generating submission reference at the beginning of the flow

package.json, server/services/redis.service.js, test/services/redis.service.test.js
IVORY-627: Address find broken
A recent fix to the Redis cache introduced a problem with arrays of objects not being returned properly. The problem manifested itself when performing an address search. This change fixes that issue.
=> Fixed Redis array issue

package.json, server/routes/service-complete.route.js
IVORY-618: Emails not sent to third party business owner
Section 2 and Section 10 emails were not being sent to the owner when the owner is a business and the application is being made by a third party (i.e. not the applicant).
The reason is that in this situation the fullName field is blank, instead we have to use the businessName field.
=> Emails not sent to third party business owner

package.json, server/index.js, server/routes/home.route.js, server/routes/service-complete.route.js, server/routes/upload-document.route.js, server/routes/upload-photo.route.js, server/services/cookie.service.js, server/services/redis.service.js, server/utils/constants.js, test/routes/home.route.test.js, test/services/cookie.service.test.js, test/services/redis.service.test.js, test/utils/test-helper.js
IVORY-621: Clear out redundant Redis data
This clears out the Redis cache for a session when the user completes the journey & also if the user was to get partially through the journey and then start again.
The Redis data has a Time to Live (TTL) of 24 hours, but if a user journey is completed or restarted then any data in Redis for that user no longer has any purpose and takes up valuable storage, therefore it is now removed using the Redis SCAN command.
=> Clear out redundant Redis data

package.json, server/index.js, server/routes/home.route.js, server/routes/use-checker.route.js, server/utils/constants.js, test/routes/home.route.test.js, test/routes/use-checker.route.test.js
IVORY-628: Provide direct access to eligibility checker
Added new **/use-checker** route to allow users to directly access the eligibility checker without having to explicitly visit the home screen.
When they visit **/use-checker** 
they are re-directed to the home screen with a querystring parameter: **/?useChecker=true**
When the user arrives at the home screen with the querystring parameter set, this creates the session cookie and then redirects them straight into the eligibility checker.
=> Provide direct access to eligibility checker

package.json, server/routes/eligibility-checker/contain-elephant-ivory.route.js, server/routes/eligibility-checker/how-certain.route.js, server/utils/general.js, test/routes/eligibility-checker/contain-elephant-ivory.route.test.js, test/routes/eligibility-checker/how-certain.route.test.js, test/utils/general.test.js
IVORY-629: Using Direct Eligibility checker link - 500 error after declaration page
Added values to Redis that are bypassed when coming in via the new /use-checker route, instead of coming in via /eligibility-checker/how-certain.
Method:
Look up the submission reference - this may have already been set in the previous screen. If not, i.e. the user came in via the new /use-checker route, then generate the submission reference and store in Redis.
Set the used-checker flag to true - this will not have been set on the previous screen if the user has come in via the new /use-checker route.
=> Add Redis values that were missing due to new /use-checker route

.env.example, README.md, package.json, server/routes/can-continue.route.js, server/services/redis.service.js, server/utils/config.js, server/views/can-continue.html
IVORY-630: Make Redis cache timeout configurable
This change utilises the existing COOKIE_TIMEOUT environment variable, which currently controls the user session timeout. This is now used to also set the Redis Time to Live (TTL) as well as to set some dynamic copy on the /can-continue page.
This will allow us to expire data from the Redis cache more quickly if we find that it is filling up with data.
=> Make Redis Time to Live (TTL) configurable

package.json, server/routes/make-payment.route.js, server/utils/config.js, test/routes/make-payment.route.test.js
IVORY-631: Provide a performance test mode
This change adds a new PERFORMANCE_TEST_MODE environment variable which, when set, causes the flow to go straight from the /make-payment route to the /service-complete route. This is for performance test purposes only and is used to bypass the following parts of the service:
- Making a Gov Pay payment
- Sending Gov Notify confirmation emails
- Saving a record in the Dataverse
In the longer term we should look to implement stubs for Gov Pay, Gov Notify and the Dataverse, but this change will allow us to complete the user journeys in the performance test mode and allow us to demonstrate that when the journeys are completed, the corresponding user session data is removed.
=> Provide performance test mode

package.json, server/routes/can-continue.route.js, server/routes/eligibility-checker/cannot-continue.route.js, server/routes/eligibility-checker/cannot-trade.route.js, server/routes/eligibility-checker/do-not-need-service.route.js, server/routes/share-details-of-item.route.js, server/utils/constants.js, server/views/layout.html, server/views/share-details-of-item.html, test/routes/can-continue.route.test.js, test/routes/do-not-need-service.route.test.js, test/routes/eligibility-checker/cannot-continue.route.test.js, test/routes/eligibility-checker/cannot-trade.route.test.js, test/routes/share-details-of-item.test.js
IVORY-609: Insert missing gov.uk guidance links into front end service
When the pages were built, the Gov UK guidance pages did not exist. The required links can now be entered into the service.
=> Added missing Gov UK links to guidance

package.json, server/plugins/views.plugin.js, server/utils/constants.js, server/views/layout.html
IVORY-639: GOV.UK in banner should link to Gov UK Home
The GOV UK link in the banner was incorrect. It was linking to: / i.e. the start of our service.
This was incorrect, instead it should link to: https://www.gov.uk
=> Updated GOV.UK banner link

Dockerfile, README.md, package-lock.json, package.json
You may or may not want this in :)
Dockerfile: split copying of package.json & lock from main app code to create a new cachable layer and speed up the rebuilds.
package.json+lock: as you'd got a postinstall there you were running npm run build twice, once after npm install and then again in dockerfile explictly. Sharp on 0.29.3 was failing to install on my M1, bumping to 0.30.1 fixes and all tests still pass.
=> Improve Docker layer structure & bump sharp

package.json, server/routes/eligibility-checker/contain-elephant-ivory.route.js, test/routes/eligibility-checker/contain-elephant-ivory.route.test.js
IVORY-675: Cannot-trade page not working due to missing species
In the EtS flow, if the user selects "Yes" to "Is it an elephant" we were not saving the species. This broke the cannot-trade page if they eventually got there.
=> Cannot-trade page not working due to missing species

server/routes/eligibility-checker/ivory-added.route.js, server/routes/eligibility-checker/taken-from-elephant.route.js, server/routes/pass-data-to-pi/application-details-pdf.route.js, server/routes/what-capacity.route.js, test/routes/what-capacity.route.test.js
IVORY-687: what-capacity page heading NOT matching the updated copy deck CD90
IVORY-689: "Already has certificate" not being set when creating application via eligibility checker
IVORY-690: Prescribed Institutions PDF download - fields are not being set properly if the item doesn't have an owner
Various front end bug fixes.
=> Front end bug fixes

server/routes/eligibility-checker/taken-from-species.route.js, test/routes/eligibility-checker/taken-from-species.route.test.js
Originally the species variable in the template would just display: "elephant" or "hippopotamus"...
The two extra options added do not make sense in this context: 
"Two or more of these species"...
"I'm not sure"...
Only displays the species' name if it's one of those defined in the constants. If not then just the word "species" is displayed instead, which makes a lot more sense.
=> Bug fix: Update taken from species page to handle new options added

server/services/odata.service.js
Fixes issues #315 and #316 
Removes cause of 404 responses when sending photos or documents to Dataverse.
Logs any errors when sending documents to Dataverse instead of silently swallowing them.
=> Log dataverse errors

server/services/cookie.service.js, test/services/cookie.service.test.js
Resolves the repeated console logging described in #317 but the issue with the root `/` endpoint being repeatedly hit is probably a health check in the environment, which will need to be investigated and probably should be calling the `/service-status` endpoint instead.
=> Stop logging cookie message when home route is accessed

Dockerfile, bin/build-css, client/sass/application.scss, package-lock.json, package.json
For #323 addressing end of life status of Node 16, moving to Node 22, which is currently LTS.
* Use `node:22` base image, which uses Debian 12 (Bookworm), upgrading from Debian 10 (Buster)
* Move from `libclamav9` to `libclamav11` as required by upgrading to Debian Bookworm
* Move from `node-sass` to Dart `sass` as `node-sass` uses `LibSass` which didn't build successfully on Debian Bookworm
* Other dependencies left as they are for now, assuming some may have issues, but will be picked up as part of work on #352
=> Update to Node 22 base image

package-lock.json, package.json, server/services/active-directory-auth.service.js, test/services/active-directory-auth.service.test.js
Upgrade to use the `msal-node` library as `adal-node` was deprecated some years ago.
Resolves #351
=> Use msal-node instead of adal-node
