server/plugins/router.js
server/routes/ivory-added.js
server/routes/ivory-is-integral.js
server/views/ivory-added.html
server/views/ivory-is-integral.html

As well as creating the "ivory-added page" I have also added the error summary to the "ivory-is-integral" page after Jordan pointed out it was missing

Ivory 301 contains replacement ivory

---

.env.example
README.md
package.json
server/config.js
server/index.js
server/plugins/redis.js
server/plugins/router.js
server/plugins/views.js
server/routes/about.js
server/views/about.html
test/home.js

Some general tidying up not related to a specific ticket

General tidy up

---

server/plugins/router.js
server/routes/check-your-answers.js
server/views/check-your-answers.html
server/views/home.html

https://eaflood.atlassian.net/jira/software/projects/IVORY/boards/341?selectedIssue=IVORY-303
Also add links to each page to the home page

Add a basic check your answers page. 

---

server/plugins/router.plugin.js
server/utils/constants.js

Dynamically add routes for paths defined in Constant.Paths. 
Also, fixed typo in route name for the 'taken-from-elephant' route that was introduced in the last commit.

Dynamically add routes for paths in Constant.Paths

---

server/plugins/logging.plugin.js
server/plugins/router.plugin.js
server/routes/check-your-answers.route.js
server/routes/ivory-added.route.js
server/routes/ivory-integral.route.js
server/routes/taken-from-elephant.route.js
server/routes/user-details/applicant/contact-details.route.js
server/routes/user-details/owner/contact-details.route.js
server/routes/who-owns-the-item.route.js
server/utils/constants.js
server/utils/validation.js
server/views/404.html
server/views/500.html
server/views/check-your-answers.html
server/views/form-layout.html
server/views/home.html
server/views/ivory-integral.html
server/views/layout.html
server/views/user-details/contact-details.html
server/views/who-owns-the-item.html
server/views/yes-no-idk.html

IVORY 307 - User provides name and email
Includes use of new form-layout.html and form validation method.
Unit tests to follow after

Ivory 307 user provides name and email

---

server/utils/general.js

Added helper method to pull data out of the request.payload and add to page context
Can be used as follows:
const { addPayloadToContext } = require('../../../utils/general')
...
const _getContext = request => {
const context = { 
title: 'Page title', 
someOtherValue: true
}
addPayloadToContext(request, context)
// Instead of, for example:
//  if (request && request.payload) {
//    context.name = request.payload.name
//    context.emailAddress = request.payload.emailAddress
//    context.confirmEmailAddress = request.payload.confirmEmailAddress
//  }
return context
}

Added helper method to pull data out of the request.payload and add to page context

---

.github/workflows/node.js.yml

Removed Node v15 from tests

---

test/routes/owner/address-international.route.test.js

Added unit test to International Address screen to increase code coverage. Fixed payload of existing test.

International Address - additional unit test

---

server/routes/check-your-answers.route.js
server/routes/what-type-of-item-is-it.route.js
server/utils/constants.js
server/views/check-your-answers.html
server/views/home.html
server/views/what-type-of-item-is-it.html
test/routes/what-type-of-item-is-it.route.test.js
test/utils/test-helper.js

Created "What is your ivory item?" page + unit tests

IVORY-321-Choose an exemption type

---

server/routes/common/address-confirm.route.js
server/routes/common/address-find.route.js
server/views/user-details/address-confirm.html
test/routes/applicant/address-confirm.route.test.js
test/routes/applicant/address-find.route.test.js
test/routes/owner/address-find.route.test.js

IVORY 330: Validation message incorrect
IVORY 331: Edit agent address - H1 heading is wrong

Address screen bug fixes 330 & 331

---

.github/workflows/node.js.yml

Updated following renaming of development branch. Also added checks to master branch

Adhoc/Updated node.js.yml after development branch renamed

---

.env.example

PAYMENT_AMOUNT split into 2 separate variables for the 2 different application costs, depending on the type of application being carried out, i.e. which option has been selected in the 'what type of item is it?' screen.
PAYMENT_AMOUNT_BAND_A=2000
PAYMENT_AMOUNT_BAND_B=25000

Updated parameters in example .env file

---

server/services/address.service.js

IVORY-327: User goes to choose address if no match on name/number
IVORY-329: How do we adapt / refine search for house name/number
This is an update to our address filtering. The address API does not allow us to pass in building name/number, we filter for this on our side.
Previously we were filtering based on exact match with either BuildingNumber, BuildingName or SubBuildingName.
Now, if there are no matches but there are results for a postcode, the user is sent to the 'Choose address' screen.
We now do partial matches, so if the user enters the full first line of their address in the building name/number field (e.g. 123 Some Street) then we handle that by matching on the corresponding address.
Also, if the user only enters part of the building name (e.g. 'barn' rather than 'The Barn') …

Fixes for 327 and 329 (refinement of address matching)

---

client/sass/application.scss
server/views/layout.html
test/utils/test-helper.js

Beta banner changed to new design

Updated beta banner

---

server/routes/your-photos.route.js
server/utils/constants.js
server/views/your-photos.html

CD71 Your photos has recently been added to the flow. This change adds a placeholder for it.

IVORY-350: Your photos placeholder

---

client/sass/application.scss
server/views/layout.html

Added a bit of custom SASS to get the text to align properly when viewed on a mobile device

IVORY-351 - Mobile - Beta banner looks a bit untidy in mobile

---

.env.example
package-lock.json
package.json
server/index.js
server/plugins/error-pages.plugin.js
server/plugins/redis.plugin.js
server/utils/config.js
server/utils/constants.js

This change adds basic authentication. By default is turned off. Can be turned on by setting the following new environment variable:
USE_BASIC_AUTH=true

Turn on basic authentication

---

.env.example
server/plugins/redis.plugin.js

Fixed Redis password problem introduced in the last commit.

Fix Redis password problem

---

server/routes/ivory-age.route.js
server/views/ivory-age.html
test/routes/ivory-age.route.test.js

IVORY-369
Added additional option, updated unit tests.

Update ivory-age options

---

package-lock.json
package.json
server/routes/eligibility-checker/are-you-a-museum.route.js
server/routes/eligibility-checker/contain-elephant-ivory.route.js
server/routes/eligibility-checker/do-not-need-service.route.js
server/routes/service-status.route.js
server/utils/constants.js
server/views/eligibility-checker/do-not-need-service.html
server/views/service-status.html
test/routes/do-not-need-service.route.test.js
test/routes/eligibility-checker/are-you-a-museum.route.test.js
test/routes/service-status.route.test.js

IVORY-379
Added content and unit tests for the "You don’t need to tell us about this item" page

"You don’t need to tell us about this item" page

---

package.json
server/plugins/views.plugin.js
server/routes/eligibility-checker/contain-elephant-ivory.route.js
server/utils/config.js

Added some missing ODataService unit tests. Fixed build issue by adding default values for Dataverse URLs.

Add unit tests, fix build issue

---

test/services/odata.service.test.js

Added unit tests to ODataService

ODataService additional unit tests

---

package.json
server/routes/can-continue.route.js
server/views/can-continue.html
test/routes/can-continue.route.test.js

IVORY-408
Added copy missing from the /can-continue page.

Added copy missing from can-continue page

---

package-lock.json
package.json
server/routes/eligibility-checker/contain-elephant-ivory.route.js
server/routes/save-record.route.js

Upgraded dependencies, fixed some SonarCloud issues.

Upgraded dependencies, fixed some SonarCloud issues.

---

server/views/can-continue.html
test/routes/can-continue.route.test.js

IVORY-416: You can continue page
Updated copy on /can-continue page

Updated copy on /can-continue page

---

server/routes/eligibility-checker/cannot-continue.route.js
test/routes/eligibility-checker/cannot-continue.route.test.js

IVORY-414: Update to 'cannot continue' page
Copy update on the following page: /eligibility-checker/cannot-continue

Update to copy on /eligibility-checker/cannot-continue page

---

server/routes/what-type-of-item-is-it.route.js
server/views/what-type-of-item-is-it.html
test/routes/what-type-of-item-is-it.route.test.js

IVORY-415: Update to the 'What type of item is it' screen
Update to the copy on the /what-type-of-item-is-it screen.

Update to the 'What type of item is it' screen

---

package.json
server/routes/eligibility-checker/how-certain.route.js
server/routes/ivory-age.route.js
server/routes/make-payment.route.js
server/routes/what-type-of-item-is-it.route.js
server/views/eligibility-checker/how-certain.html
server/views/ivory-age.html
server/views/legal-responsibility.html
server/views/upload-document.html
server/views/upload-photo.html
server/views/user-details/address-enter.html
server/views/user-details/address-find.html
server/views/user-details/contact-details.html
server/views/what-type-of-item-is-it.html
test/routes/eligibility-checker/how-certain.route.test.js
test/routes/ivory-age.route.test.js
test/routes/legal-responsibility.route.test.js
test/routes/make-payment.route.test.js
test/routes/upload-document.route.test.js
test/routes/upload-photo.route.test.js
test/routes/what-type-of-item-is-it.route.test.js

IVORY-400: Design QA of the Dev environment
This change includes fixes to various screens where the design had moved on but the development had not been carried out.

Various minor screen amendments

---

package.json
server/routes/ivory-age.route.js
test/routes/ivory-age.route.test.js

IVORY-421: Missing CD72 - Do you want to add any documents to support your application?
The page flow was incorrect and the screen for CD72 was not included in the flow.

Fix flow to add missing page

---

package.json
server/routes/eligibility-checker/cannot-continue.route.js
server/routes/eligibility-checker/contain-elephant-ivory.route.js
server/views/eligibility-checker/cannot-continue.html
test/routes/eligibility-checker/cannot-continue.route.test.js
test/routes/eligibility-checker/contain-elephant-ivory.route.test.js

IVORY-425
Fixed incorrect help text on .../cannot-continue screen

Fixed incorrect help text on .../cannot-continue screen

---

package.json
server/views/eligibility-checker/do-not-need-service.html
test/routes/do-not-need-service.route.test.js

IVORY-430
Updated call to action button text since we don't have guidance at the moment.

Updated button on ../do-not-need-service page

---

package.json
server/routes/check-your-answers.route.js
server/routes/legal-responsibility.route.js
server/views/check-your-answers.html
test/routes/check-your-answers.route.test.js
test/routes/legal-responsibility.route.test.js

IVORY-448: Changes to legal declarations
Changes to the legal declarations on the /legal-responsibility and /check-your-answers pages.

Changes to legal declarations

---

package.json
server/routes/upload-document.route.js
server/routes/upload-photo.route.js

As discussed I've added a couple of awaits to the RedisService to see if that resolves this bug

added awaits to redis service

---

package-lock.json
package.json
server/routes/save-record.route.js
test/routes/save-record.route.test.js

IVORY-505: Previous submission details missing in PowerAps
Added missing previous submission details for RMI resale journey.

Added missing previous submission details for resale route

---

package.json
server/routes/check-your-answers.route.js
server/services/redis-helper.service.js
server/views/check-your-answers.html
test/routes/check-your-answers.route.test.js

IVORY-506: Legal declarations for resale journey
Fixes dynamic copy that was missing from the RMI resale journey.

Added legal declarations for RMI resale journey

---

package.json
server/routes/check-your-answers.route.js
server/routes/common/address-confirm.route.js
server/routes/make-payment.route.js
server/routes/pass-data-to-pi/application-details-pdf.route.js
server/routes/pass-data-to-pi/application-details.route.js
server/routes/save-record.route.js
server/routes/service-complete.route.js
test/mock-data/section-2-entity.js
test/routes/applicant/address-confirm.route.test.js
test/routes/owner/address-confirm.route.test.js
test/routes/pass-data-to-pi/application-details.route.test.js
test/routes/service-complete.route.test.js

IVORY-522: Legal change - GOV Pay item description
IVORY-528: Address formatting
Implemented legal changes - the item description on the GOV Pay screen has been updated for the three types of transaction.
Also, fixed bug 528, which standardises the formatting of addresses throughout the service.

GOV Pay item description and address formatting

---

package.json
server/routes/applied-before.route.js
server/routes/check-your-answers.route.js
server/routes/eligibility-checker/how-certain.route.js
server/utils/constants.js
server/views/already-certified.html
test/routes/already-certified.route.test.js
test/routes/applied-before.route.test.js
test/routes/check-your-answers.route.test.js
test/routes/eligibility-checker/how-certain.route.test.js
test/routes/ivory-integral.route.test.js

IVORY-518: Small content tweaks to multiple screens

Various legal changes - small content tweaks to multiple screens

---

package.json
server/routes/service-complete.route.js
test/routes/service-complete.route.test.js

IVORY-520: Confirmation page legal changes
Content updates to 'what happens next' section, multiple scenarios

Confirmation page legal changes

---

package.json
server/routes/upload-document.route.js
server/routes/want-to-add-documents.route.js
server/routes/your-documents.route.js
server/views/upload-document.html
server/views/want-to-add-documents.html
server/views/your-documents.html
test/routes/remove-document.route.test.js
test/routes/upload-document.route.test.js
test/routes/want-to-add-documents.route.test.js
test/routes/your-documents.route.test.js

IVORY-523: Supporting evidence legal changes
Updates to S2 adding supporting evidence/documents flow.

Supporting evidence legal changes

---

package.json
server/routes/eligibility-checker/rmi-and-pre-1918.route.js
server/views/eligibility-checker/is-it-rmi.html
server/views/eligibility-checker/rmi-and-pre-1918.html
server/views/why-is-item-rmi.html
test/routes/eligibility-checker/is-it-rmi.route.test.js
test/routes/eligibility-checker/rmi-and-pre-1918.route.test.js
test/routes/why-is-item-rmi.route.test.js

IVORY-524: RMI screens legal changes
Updates to RMI definition across multiple screens

RMI screens legal changes

---

package.json
server/routes/selling-on-behalf-of.route.js
test/routes/selling-on-behalf-of.route.test.js

IVORY-540: Selling on behalf of
'Selling on behalf of' question update.

Selling on bahalf of legal changes

---

package.json
server/routes/already-certified.route.js
server/routes/eligibility-checker/selling-to-museum.route.js
server/routes/work-for-a-business.route.js
server/views/eligibility-checker/do-not-need-service.html
test/routes/already-certified.route.test.js
test/routes/do-not-need-service.route.test.js
test/routes/eligibility-checker/selling-to-museum.route.test.js
test/routes/work-for-a-business.route.test.js

IVORY-541: Sell or hire legal changes
'Sell or hire' content tweaks across multiple pages.
Also, bugs IVORY-544 and IVORY-545.

Sell or hire legal changes

---

package.json
server/views/eligibility-checker/is-it-rmi.html
test/routes/eligibility-checker/is-it-rmi.route.test.js

IVORY-549: Is it RMI page copy bugs
Fixed copy bugs in the Is it RMI page

Fixed copy bugs in the Is it RMI page

---

package.json
server/plugins/airbrake.plugin.js
server/routes/accessibility-statement.route.js
server/routes/check-your-answers.route.js
server/routes/cookie-policy.route.js
server/routes/describe-the-item.route.js
server/routes/download-certificate.route.js
server/routes/eligibility-checker/made-before-1975.route.js
server/routes/errors/record-not-found.route.js
server/routes/make-payment.route.js
server/routes/pass-data-to-pi/application-details-pdf.route.js
server/routes/pass-data-to-pi/application-details.route.js
server/routes/pass-data-to-pi/application-documents.route.js
server/routes/pass-data-to-pi/application-photos.route.js
server/routes/privacy-notice.route.js
server/routes/remove-document.route.js
server/routes/remove-photo.route.js
server/routes/save-record.route.js
server/routes/user-details/owner/contact-details.route.js
server/routes/what-capacity.route.js
server/services/odata.service.js
server/services/redis-helper.service.js
test/services/odata.service.test.js

Various SonarCloud issues fixed, some more still to, which will be done in a separate change.

Fix various sonar cloud issues

---

package.json
server/plugins/error-pages.plugin.js
server/routes/common/address-confirm.route.js
server/routes/common/address-find.route.js
server/routes/eligibility-checker/are-you-a-museum.route.js
server/routes/eligibility-checker/is-it-a-musical-instrument.route.js
server/routes/eligibility-checker/is-it-rmi.route.js
server/routes/errors/record-not-found.route.js
server/services/address.service.js
server/services/payment.service.js
server/utils/config.js
server/utils/general.js
test/routes/errors/record-not-found.route.test.js
test/utils/general.test.js

Refactored to address some further SonarCloud issues. Also added a unit test file for the record-not-found route.

Fixed further SonarCloud issues, added unit test

---

package.json
server/routes/check-your-answers.route.js
server/views/check-your-answers.html
server/views/pass-data-to-pi/application-details.html
test/routes/check-your-answers.route.test.js
test/routes/pass-data-to-pi/application-details.route.test.js

IVORY-588: Check your answers page - Updated legal change content not appearing
Modified copy that was recently amended but missed from the last set of legal changes that were developed.

Check your answers page - Updated legal change content not appearing 

---

package.json
server/routes/eligibility-checker/are-you-a-museum.route.js
test/routes/eligibility-checker/are-you-a-museum.route.test.js

IVORY:545 - Are you a museum page - missing copy
Added missing copy to are-you-a-museum page

Are you a museum page - missing copy

---

client/sass/application.scss
package.json

IVORY-577: Legal responsibility: change Interruption (blue) card hover colour
Fixed accessibility issue - changed hover colour for button on the /legal-responsibility page.

Fixed accessibility issue - changed button hover colour

---

server/index.js

Fixed position of ApplicationInsights and fixed cloudRoleName not being set correctly

AppInsights tweaks

---

package.json
server/routes/check-your-answers.route.js
server/services/redis-helper.service.js
test/routes/check-your-answers.route.test.js
test/services/redis-helper.service.test.js

IVORY-666: Check your answers page - Portrait miniature problem
Hide the "Proof it has less than x%" value in Check your answers page for portrait miniatures

Check your answers - portrait miniatures bug

---

jest.setEnvVars.js
package.json
server/routes/cookie-policy.route.js
server/routes/eligibility-checker/contain-elephant-ivory.route.js
server/routes/eligibility-checker/what-species.route.js
server/utils/config.js
server/views/cookie-policy.html
server/views/eligibility-checker/contain-elephant-ivory.html
test/routes/can-continue.route.test.js
test/routes/eligibility-checker/contain-elephant-ivory.route.test.js
test/routes/eligibility-checker/what-species.route.test.js
test/services/redis.service.test.js

IVORY-676: Contain elephant ivory page copy
IVORY-681: ETS - Eligibility checker - Flow NOT correct
Fixed copy on elephant ivory page. Also, fixed cookie timeout error on cookie page - made time dynamic based on config. Fixed jest cookie config for unit tests.
Fixed incorrect page flow following the what-species page.

Contain elephant ivory page copy

---

.gitignore
package-lock.json
server/routes/check-your-answers.route.js
test/routes/check-your-answers.route.test.js
test/utils/test-helper.js

Validation on the check your answers page.

163724 validate required data check your answers

---

server/routes/save-record.route.js
server/services/odata.service.js
test/routes/save-record.route.test.js
test/services/odata.service.test.js

- Refactored the code to update each additional photo in the separate Odata call

164949 - Split photo API calls into separate calls

---

server/routes/check-your-answers.route.js
test/routes/check-your-answers.route.test.js

- Updated the legal assertion to no more than as requested by Liezel

changing the legal assertion to no more than 320

---

server/views/describe-the-item.html

Liezel requested for character component instead of text input

164888 - character count component instead of text input

---

package.json

- Incremented the version number for prod release

Increasing the version number to 1.4.4

---

server/routes/check-your-answers.route.js
server/routes/eligibility-checker/cannot-trade.route.js
server/routes/eligibility-checker/selling-to-museum.route.js
server/routes/eligibility-checker/taken-from-species.route.js
server/views/eligibility-checker/cannot-continue.html
server/views/eligibility-checker/less-than-10-ivory.html
server/views/eligibility-checker/selling-to-museum.html
test/routes/check-your-answers.route.test.js
test/routes/eligibility-checker/cannot-trade.route.test.js
test/routes/eligibility-checker/less-than-10-ivory.route.test.js
test/routes/eligibility-checker/selling-to-museum.route.test.js
test/routes/eligibility-checker/taken-from-species.route.test.js

This reverts commit 1a1f607a934375b828b8657df46ca578a38825ed, reversing changes made to db6b50f8c9cdf78127cc1c6299e64f036e7fb29e.

Revert 2 - Latest text changes - Merge into revert-1 branch if required

---

package-lock.json
package.json
server/plugins/views.plugin.js
server/routes/check-your-answers.route.js
server/routes/save-record.route.js
server/services/odata.service.js
test/services/notification.service.test.js
test/services/payment.service.test.js

Updated to standard v17, minor code formatting changes as required.
Resolves #362

Updated to StandardJS 17

---

server/routes/public.route.js
test/routes/public.route.test.js

Serve favicon from root
